name: energy_workflow

on: repository_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering [Energy] Wokflow 2"
      - run: echo "Event type -> ${{ github.event.event_type }}"
      - run: echo "Payload repo -> ${{ github.event.client_payload.repository }}"
      - name: Checkout
        uses: actions/checkout@v3
